// Catalog of Hymn titles recognized by the church library
export const KNOWN_HYMN_TITLES = [
  'A Mighty Fortress Is Our God',
  'Abide With Me',
  'Alas And Did My Saviour Bleed',
  'All Creatures Of Our God And King',
  "All Hail The Power Of Jesus' Name",
  'All My Heart This Night Rejoices',
  'All My Hope On God Is Founded',
  'All People That On Earth Do Dwell',
  'All Things Bright And Beautiful',
  'Alleluia Sing To Jesus',
  'Amazing Grace (My Chains Are Gone)',
  'And Can It Be',
  'And Did Those Feet In Ancient Time',
  'Angel Voices Ever Singing',
  'Angels From The Realms Of Glory',
  'Angels We Have Heard On High',
  'Are You Washed in the Blood',
  'As With Gladness Men Of Old',
  'At Calvary',
  'At the Name of Jesus',
  'Away In A Manger',
  'Battle Hymn Of The Republic',
  'Be Thou My Vision',
  'Because He Lives',
  'Before The Throne Of God Above',
  'Beneath The Cross Of Jesus',
  'Blessed Be The Name',
  'Blest Be The Tie',
  'Break Thou The Bread Of Life',
  'Breathe On Me Breath Of God',
  'Child In The Manger',
  'Christ Arose',
  'Christ the Lord Is Risen Today',
  'Christ Whose Glory Fills The Skies',
  'Christians Awake',
  'Come Down O Love Divine',
  'Come Let Us Join Our Cheerful Songs',
  'Come Let Us Sing Of A Wonderful Love',
  'Come Thou Fount',
  'Come Thou Fount Of Every Blessing',
  'Come Thou Long Expected Jesus',
  'Come Ye Thankful People Come',
  'Come, Thou Almighty King',
  'Crown Him With Many Crowns',
  'Dear Lord And Father Of Mankind',
  'Ding Dong Merrily On High',
  'Draw Me Nearer',
  'Dwelling in Beulah Land',
  'Eternal Father Strong To Save',
  'Fairest Lord Jesus',
  'Faith Of Our Fathers',
  'Father Hear The Prayer We Offer',
  'Forth In Thy Name O Lord I Go',
  'Give Me Jesus',
  'Glory To His Name',
  'Go Tell It On The Mountain',
  'God Be With You',
  'God Is Love Let Heaven Adore Him',
  'God Is Working His Purpose Out',
  'God Moves In A Mysterious Way',
  'God Rest Ye Merry Gentlemen',
  'Good Christian Men Rejoice',
  'Grace Greater Than Our Sin',
  'Guide Me, O Thou Great Redeemer',
  'Hail Thou Once Despised Jesus',
  "Hail To The Lord's Anointed",
  'Happiness Is The Lord',
  'Hark! The Herald Angels Sing',
  'Have Thine Own Way',
  'He Giveth More Grace',
  'He Hideth My Soul',
  'He Leadeth Me',
  'He Leadeth Me O Blessed Thought',
  'He Look Beyond My Fault',
  'He Touched Me',
  'He Who Would Valiant Be',
  "He's Got The Whole World In His Hands",
  "He's Still Working On Me",
  'Here Is Love',
  'Higher Ground',
  'His Eye Is On The Sparrow',
  'Holy Holy Holy',
  'How Deep The Father\'s Love Is',
  'How Firm A Foundation',
  'How Great Thou Art',
  'How Lovely Is Thy Dwelling Place',
  'How Sweet The Name Of Jesus Sounds',
  'I Am Resolved',
  'I Am Thine, O Lord',
  'I Cannot Tell',
  'I Have Decided To Follow Jesus',
  'I Heard The Voice Of Jesus Say',
  'I Know That My Redeemer Lives',
  'I Know Who Holds Tomorrow',
  'I Know Whom I Have Believed',
  'I Need Thee Every Hour',
  'I Saw Three Ships',
  'I Surrender All',
  'I Will Sing The Wondrous Story',
  "I'd Rather Have Jesus",
  "I'm Not Ashamed To Own My Lord",
  "I'm Standing on The Solid Rock",
  "I've Been Changed/Since Jesus Came into My Heart (Medley)",
  'In Christ Alone',
  'In Christ Alone My Hope is Found',
  'In Heavenly Love Abiding',
  'In The Bleak Midwinter',
  'In the Garden',
  'In the Sweet By and By',
  'It Came Upon The Midnight Clear',
  'It Is A Thing Most Wonderful',
  'It Is Well With My Soul',
  'Jesus Christ is Risen Today',
  'Jesus I My Cross Have Taken',
  'Jesus Keep Me Near The Cross',
  'Jesus Lover Of My Soul',
  'Jesus Loves Even Me',
  'Jesus Loves Me This I Know',
  'Jesus Never Fails',
  'Jesus Paid It All',
  'Jesus Saves (Hymn)',
  'Jesus Saves (Tell The World Around Me)',
  'Jesus Shall Reign',
  'Jesus The Name High Over All',
  'Join All The Glorious Names',
  'Joy To The World',
  'Joyful Joyful We Adore Thee',
  'Just As I Am',
  'King Of Glory King Of Peace',
  'King Of My Life I Crown Thee Now',
  'Lead Us Heavenly Father Lead Us',
  'Leaning On The Everlasting Arms',
  'Lo He Comes With Clouds Descending',
  'Look Ye Saints The Sight Is Glorious',
  'Lord Enthroned In Heavenly Splendour',
  'Love Came Down At Christmas',
  'Love Divine',
  "Love's Redeeming Work Is Done",
  'Low In The Grave He Lay',
  'Make Me A Blessing',
  'Man of Sorrows',
  'Mansion Over The Hilltop',
  'May The Mind Of Christ My Saviour',
  'My Faith Has Found A Resting Place',
  'My Jesus I Love Thee',
  "My Saviour's Love",
  'My Song Is Love Unknown',
  'My Tribute',
  'Nearer My God To Thee',
  'No One ever Cared For Me Like Jesus',
  'Nothing But The Blood',
  'Now I Belong to Jesus',
  'Now Thank We All Our God',
  'O Breath Of Life',
  'O Come All Ye Faithful',
  'O Come Emmanuel Medley',
  'O Come O Come Emmanuel',
  'O For A Heart To Praise My God',
  'O For A Thousand Tongues To Sing',
  'O Happy Day',
  'O Holy Night',
  'O How I love Jesus',
  'O Jesus I Have Promised',
  'O Little Town Of Bethlehem',
  'O Love That Wilt Not Let Me Go',
  'O Sacred Head',
  'O The Deep Deep Love Of Jesus',
  'O Worship The King',
  'O Worship The Lord In The Beauty Of Holiness',
  "Once In Royal David's City",
  'One Day When Heaven',
  'Onward Christian Soldiers',
  'Praise God From Whom All Blessings Flow',
  'Praise Him Praise Him',
  'Praise My Soul The King Of Heaven',
  'Praise To The Holiest In The Height',
  'Praise To The Lord The Almighty',
  'Redeemed',
  'Rejoice The Lord Is King',
  'Revive Us Again',
  'Rock Of Ages',
  'Salvation Unto Us Has Come',
  'Saved! Saved!',
  'Saviour Again',
  "See Amid The Winter's Snow",
  'Send The Fire',
  'Send the Light',
  'Silent Night',
  'Since I Have Been Redeemed',
  'Since I Have Been Redeemed (1)',
  'Since Jesus Came Into My Heart',
  'Stand Up Stand Up For Jesus',
  'Standing On The Promises',
  'Stepping In The Light',
  'Sunshine in My Soul',
  'Surely Goodness and Mercy',
  'Sweet Hour of Prayer',
  'Take My Hand Precious Lord',
  'Take My Life And Let It Be',
  'Tell It To Jesus',
  'The Angel Gabriel From Heaven Came',
  'The Banner Of The Cross',
  "The Blood Will Never Lose It's Power",
  "The Church's One Foundation",
  'The Day Of Resurrection',
  'The Day Thou Gavest Lord Is Ended',
  'The First Noel',
  'The God Of Abraham Praise',
  'The Head That Once Was Crowned With Thorns',
  'The King Is Coming',
  'The King Of Love',
  'The Lily Of The Valley',
  'The Longer I Serve Him',
  'The Lord Jehovah Reigns',
  "The Lord's My Shepherd",
  'The Love of God',
  'The Old Rugged Cross',
  'The Solid Rock',
  "The Strife Is O'er",
  'There Is A Fountain',
  'There is a Green Hill Far Away',
  'There Is Power In The Blood',
  'Thine Be The Glory',
  'This World Is Not My Home',
  'Through All The Changing Scenes Of Life',
  'Thy Hand O God Has Guided',
  'Tis Finished The Messiah Dies',
  'Tis So Sweet To Trust In Jesus',
  'To God Be The Glory',
  'To The Work',
  'Victory In Jesus',
  'We Plough The Fields And Scatter',
  'We Rest On Thee Our Shield And Our Defender',
  'We Sing the Praise Of Him Who Died',
  'We Three Kings',
  "We'll work till Jesus comes,",
  "We've A Story To Tell To The Nations",
  'Were You There',
  'What a Day That Will Be',
  'What a Friend We Have in Jesus',
  'What Child Is This',
  'When I Survey the Wondrous Cross',
  'When The Roll Is Called Up Yonder',
  'When We All Get To Heaven',
  'When We See Christ',
  'When We Walk With The Lord',
  'While Shepherds Watched',
  'Who Is He In Yonder Stall',
  'Why Not Today',
  'Will Your Anchor Hold',
  'Wonderful Grace Of Jesus',
  'Wonderful Words of Life',
  'Ye Servants Of God',
];

function normalizeTitle(title: string): string {
  return (title || '')
    .toLowerCase()
    .replace(/['’]/g, "'")
    .replace(/[^a-z0-9]/g, '');
}

const KNOWN_HYMN_NORMALIZED_SET = new Set(KNOWN_HYMN_TITLES.map(normalizeTitle));

export function isKnownHymnTitle(title: string): boolean {
  return KNOWN_HYMN_NORMALIZED_SET.has(normalizeTitle(title));
}
